# Generated by Django 5.1.4 on 2025-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
