# Generated by Django 5.1.4 on 2025-01-23 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0003_blog_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog_post",
            name="post_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
