# Generated by Django 5.1.4 on 2025-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0004_blog_post_post_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="xray_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xray_image", models.ImageField(upload_to="x_rays_uploaded")),
            ],
        ),
    ]
