# Generated by Django 5.1.4 on 2025-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0005_xray_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xray_image",
            name="xray_image",
            field=models.ImageField(upload_to="x_rays_uploaded/"),
        ),
    ]
