# Generated by Django 5.1.4 on 2025-02-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0007_xray_image_xray_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="phoneno",
        ),
    ]
