# Generated by Django 5.1.4 on 2025-02-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0008_rename_bio_profile_phoneno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xray_image",
            name="xray_author",
        ),
    ]
