# Generated by Django 5.1.4 on 2025-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0009_remove_xray_image_xray_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("message", models.TextField(max_length=100)),
            ],
        ),
    ]
