# Generated by Django 5.1.4 on 2025-02-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0010_contact_us"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="media/profile_pictures/default.png",
                upload_to="profile_pictures/",
            ),
        ),
    ]
