# Generated by Django 5.1.4 on 2025-03-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0011_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="blog_post",
        ),
    ]
