# Generated by Django 5.1.4 on 2025-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0013_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor_name",
            field=models.CharField(default=False, max_length=100),
        ),
    ]
